//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_6_DB_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.MM_Tours_Clients = new HashSet<MM_Tours_Clients>();
        }
    
        public int ID_client { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MIddle_name { get; set; }
        public string Phone_number { get; set; }
        public System.DateTime Date_birth { get; set; }
        public string Email { get; set; }
        public System.DateTime Registration_date { get; set; }
        public string HomeTown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Tours_Clients> MM_Tours_Clients { get; set; }
    }
}
