//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_6_DB_first
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Green_resortEntities : DbContext
    {
        public Green_resortEntities()
            : base("name=Green_resortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Dwelling> Dwellings { get; set; }
        public virtual DbSet<Entertainment> Entertainments { get; set; }
        public virtual DbSet<MM_Tours_Clients> MM_Tours_Clients { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<Tours_Entertainments> Tours_Entertainments { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<Workers_Tours> Workers_Tours { get; set; }
    }
}
