//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_6_DB_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Tours_Clients
    {
        public int ID_tours { get; set; }
        public int ID_clients { get; set; }
        public int ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
