//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_6_DB_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.MM_Tours_Clients = new HashSet<MM_Tours_Clients>();
            this.Tours_Entertainments = new HashSet<Tours_Entertainments>();
            this.Workers_Tours = new HashSet<Workers_Tours>();
        }
    
        public int ID_tour { get; set; }
        public bool Food { get; set; }
        public int Cost { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public int ID_dwelling { get; set; }
        public Nullable<System.DateTime> Date_order { get; set; }
        public Nullable<bool> Pet { get; set; }
        public Nullable<bool> Smoking { get; set; }
    
        public virtual Dwelling Dwelling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Tours_Clients> MM_Tours_Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tours_Entertainments> Tours_Entertainments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workers_Tours> Workers_Tours { get; set; }
    }
}
